version: '3.8'

services:
  dev:
    container_name: nodejs-api-dev
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    restart: unless-stopped

  test:
    container_name: nodejs-api-test
    build:
      context: .
      target: test
    volumes:
      - .:/app
      - /app/node_modules

  prod:
    container_name: nodejs-api-prod
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
    restart: unless-stopped