name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker compose build dev

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run linting
        run: docker compose run dev npm run lint:check

  format:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run format check
        run: docker compose run dev npm run format:check

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: docker compose run dev npm run test

  push-image-to-dockerhub:
    needs: [lint, format, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get short commit hash
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push with commit hash tag
        run: |
          docker compose build dev
          docker tag ci-cd-pipeline-dev mdtazbinur/example-app:${{ steps.vars.outputs.sha_short }}
          docker push mdtazbinur/example-app:${{ steps.vars.outputs.sha_short }}

  deploy-to-AWS-EC2:
    needs: push-image-to-dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to AWS-EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER_NAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull mdtazbinur/example-app:${{ steps.vars.outputs.sha_short }}
            if [ "$(docker ps -f name=example-app-api -q)" ]; then
              docker stop example-app-api
            fi
            if [ "$(docker ps -a -f name=example-app-api -q)" ]; then
              docker rm example-app-api
            fi
            docker run -d --name example-app-api -p 80:3000 mdtazbinur/example-app:${{ steps.vars.outputs.sha_short }}
