name: CI-check-format

on:
  pull_request:
    branches:
      - master

jobs:

  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and run formatting check
        run: |
          docker compose build dev
          docker compose run dev npm run format:check
