name: PR Checks

on:
  pull_request:
    branches:
      - '*'

jobs:
  build-dev-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker compose build dev

  check-code-lint:
    needs: build-dev-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run linting
        run: docker compose run dev npm run lint:check

  check-code-format:
    needs: build-dev-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run format check
        run: docker compose run dev npm run format:check

  run-test-cases:
    needs: build-dev-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: docker compose run dev npm run test
